[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.branch-deploy]
  [context.branch-deploy.environment]
    VUE_APP_BASE_URL = "/"
    VUE_APP_API_URL = "https://altpower-staging.herokuapp.com/v1/"
    VUE_APP_PAYSTACK_KEY = "pk_test_a5e5a7ad89b8d468a6482b29dcf2acd7b09a1c18"


[context.deploy-preview]
  [context.deploy-preview.environment]
    VUE_APP_BASE_URL = "/"
    VUE_APP_API_URL = "https://altpower-staging.herokuapp.com/v1/"
    VUE_APP_PAYSTACK_KEY = "pk_test_a5e5a7ad89b8d468a6482b29dcf2acd7b09a1c18"


[context.production]
  [context.production.environment]
    VUE_APP_MODE = "production"
